<?php
require_once __DIR__ . '/../includes/auth.php';

redirectIfNotLoggedIn();
if (!isStaff()) {
    header('HTTP/1.0 403 Forbidden');
    exit();
}

$patientId = isset($_GET['id']) ? intval($_GET['id']) : 0;
$format = isset($_GET['format']) ? $_GET['format'] : 'excel';

if ($patientId <= 0) {
    header('HTTP/1.0 400 Bad Request');
    exit();
}

try {
    // Get patient basic information
    $stmt = $pdo->prepare("SELECT p.*, u.unique_number, u.email as user_email 
                          FROM sitio1_patients p 
                          LEFT JOIN sitio1_users u ON p.user_id = u.id
                          WHERE p.id = ? AND p.added_by = ?");
    $stmt->execute([$patientId, $_SESSION['user']['id']]);
    $patient = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$patient) {
        header('HTTP/1.0 404 Not Found');
        exit();
    }
    
    // Get health information
    $stmt = $pdo->prepare("SELECT * FROM existing_info_patients WHERE patient_id = ?");
    $stmt->execute([$patientId]);
    $healthInfo = $stmt->fetch(PDO::FETCH_ASSOC);
    
    // Get visit history
    $stmt = $pdo->prepare("SELECT * FROM patient_visits WHERE patient_id = ? ORDER BY visit_date DESC");
    $stmt->execute([$patientId]);
    $visits = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
} catch (PDOException $e) {
    header('HTTP/1.0 500 Internal Server Error');
    exit();
}

// Set filename
$filename = "patient_record_" . preg_replace('/[^a-zA-Z0-9]/', '_', $patient['full_name']) . "_" . date('Y-m-d');

if ($format === 'excel') {
    // Export to Excel
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment; filename="' . $filename . '.xls"');
    
    $output = "<table border='1'>";
    $output .= "<tr><th colspan='4' style='background-color: #ccc;'>PATIENT HEALTH RECORD</th></tr>";
    $output .= "<tr><th colspan='4' style='background-color: #eee;'>Personal Information</th></tr>";
    $output .= "<tr><th>Full Name</th><td>" . htmlspecialchars($patient['full_name']) . "</td><th>Age</th><td>" . ($patient['age'] ?? 'N/A') . "</td></tr>";
    $output .= "<tr><th>Gender</th><td>" . (isset($patient['gender']) && $patient['gender'] ? htmlspecialchars($patient['gender']) : 'N/A') . "</td><th>Contact</th><td>" . htmlspecialchars($patient['contact'] ?? 'N/A') . "</td></tr>";
    $output .= "<tr><th>Address</th><td colspan='3'>" . htmlspecialchars($patient['address'] ?? 'N/A') . "</td></tr>";
    $output .= "<tr><th>Last Check-up</th><td>" . ($patient['last_checkup'] ? date('F j, Y', strtotime($patient['last_checkup'])) : 'N/A') . "</td><th>User Type</th><td>" . (!empty($patient['unique_number']) ? 'Registered User' : 'Regular Patient') . "</td></tr>";
    
    $output .= "<tr><th colspan='4' style='background-color: #eee;'>Health Information</th></tr>";
    $output .= "<tr><th>Height</th><td>" . ($healthInfo['height'] ?? 'N/A') . " cm</td><th>Weight</th><td>" . ($healthInfo['weight'] ?? 'N/A') . " kg</td></tr>";
    $output .= "<tr><th>Blood Type</th><td>" . htmlspecialchars($healthInfo['blood_type'] ?? 'N/A') . "</td><th>Allergies</th><td>" . htmlspecialchars($healthInfo['allergies'] ?? 'None') . "</td></tr>";
    $output .= "<tr><th>Medical History</th><td colspan='3'>" . htmlspecialchars($healthInfo['medical_history'] ?? 'None') . "</td></tr>";
    $output .= "<tr><th>Current Medications</th><td colspan='3'>" . htmlspecialchars($healthInfo['current_medications'] ?? 'None') . "</td></tr>";
    $output .= "<tr><th>Family History</th><td colspan='3'>" . htmlspecialchars($healthInfo['family_history'] ?? 'None') . "</td></tr>";
    
    if (!empty($visits)) {
        $output .= "<tr><th colspan='5' style='background-color: #eee;'>Visit History</th></tr>";
        $output .= "<tr><th>Date</th><th>Reason</th><th>Diagnosis</th><th>Treatment</th><th>Notes</th></tr>";
        
        foreach ($visits as $visit) {
            $output .= "<tr>";
            $output .= "<td>" . date('M j, Y', strtotime($visit['visit_date'])) . "</td>";
            $output .= "<td>" . htmlspecialchars($visit['reason'] ?? 'N/A') . "</td>";
            $output .= "<td>" . htmlspecialchars($visit['diagnosis'] ?? 'N/A') . "</td>";
            $output .= "<td>" . htmlspecialchars($visit['treatment'] ?? 'N/A') . "</td>";
            $output .= "<td>" . htmlspecialchars($visit['notes'] ?? 'N/A') . "</td>";
            $output .= "</tr>";
        }
    }
    
    $output .= "<tr><th colspan='5' style='background-color: #eee;'>Report Information</th></tr>";
    $output .= "<tr><th>Generated By</th><td colspan='4'>" . htmlspecialchars($_SESSION['user']['full_name'] ?? 'System') . "</td></tr>";
    $output .= "<tr><th>Generated On</th><td colspan='4'>" . date('F j, Y, g:i a') . "</td></tr>";
    
    $output .= "</table>";
    
    echo $output;
    exit();
    
} elseif ($format === 'pdf') {
    // For PDF export, we'll use a library like TCPDF or Dompdf
    // This is a placeholder - you'll need to install and configure a PDF library
    
    // Example using TCPDF (you need to install it first):
    /*
    require_once('tcpdf/tcpdf.php');
    
    $pdf = new TCPDF();
    $pdf->AddPage();
    $pdf->SetFont('helvetica', '', 12);
    
    // Add content to PDF
    $content = "PATIENT HEALTH RECORD\n\n";
    $content .= "Personal Information\n";
    $content .= "Full Name: " . $patient['full_name'] . "\n";
    $content .= "Age: " . ($patient['age'] ?? 'N/A') . "\n";
    // Add more content...
    
    $pdf->Write(0, $content);
    
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="' . $filename . '.pdf"');
    
    $pdf->Output('php://output', 'D');
    exit();
    */
    
    // For now, we'll redirect to the print version
    header('Location: print_patient.php?id=' . $patientId);
    exit();
}
?>